### PR TITLE
Expanded Abbreviation Mappings

### PR DESCRIPTION
**Pull request by Advitya17**
We've included more Acronyms as per Johnson Control's website.

Please let me know if any changes may need to be made. Thank you!

### CODE REVIEW

**Comment by epaulson** [comment]
Hi @Advitya17 - this looks like a good list. We're gonna take just a bit more time to review it but I think we'll merge it soon. 

Thanks!

**Comment by Advitya17** [comment]
Hi @epaulson, thank you for your response! Please let me know if any corrections need to be made, due to partial manual interventions made for this PR. 

Additionally, there are more documentations (especially outdated or legacy ones) by Johnson Controls with more abbreviations that may still be utilized in point labels at present. Hence this list is not complete and there are additional contributions my group seeks to make over the next 2 weeks as much as feasible. 

Depending upon encountered use cases, the API can be subject to gradual/continued improvements in the future.

**Comment by epaulson** [comment]
Do you want us to wait for two weeks or so before merging?

**Comment by epaulson** [comment]
Thanks for talking with us today @Advitya17  - do let us know when this is set to merge - no rush, take your time!

**Comment by gtfierro** [comment]
@Advitya17 I wanted to follow up on this PR --- are there future changes you would like to incorporate so that we can merge?

**Comment by Advitya17** [comment]
Hi @gtfierro , sorry for the delay in response. No future changes for now. As mentioned before, this may stay a continual work in progress depending upon specific use cases that may arise. Thanks a lot!

**Pull request merged**
